import React, { useState, useEffect, useRef } from 'react';
import Markdown from 'react-markdown';
import { NewsPost, PostFormat, ReportLanguage } from '../types';
import { INITIAL_NEWS } from '../constants';
import { 
  Plus, Trash2, Layout, Image as ImageIcon, Type, Tag, 
  Calendar, Save, AlertCircle, Youtube, X, Upload, 
  Edit3, Eye, Sparkles, Loader2, ChevronRight, ChevronLeft
} from 'lucide-react';
import { generateDailyForecast } from '../services/geminiService';

const AdminPanel: React.FC = () => {
  const [posts, setPosts] = useState<NewsPost[]>([]);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formData, setFormData] = useState<Partial<NewsPost>>({
    format: 'fact',
    topic: 'astrology',
    date: new Date().toISOString().split('T')[0],
    images: []
  });
  const [error, setError] = useState('');
  const [success, setSuccess] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [aiPrompt, setAiPrompt] = useState('');
  const [aiLang, setAiLang] = useState<ReportLanguage>('English');
  const [showPreview, setShowPreview] = useState(false);
  const fileInputRef = useRef<HTMLInputElement>(null);

  useEffect(() => {
    console.log('AdminPanel mounted');
    const fetchPosts = async () => {
      try {
        const response = await fetch('/api/news');
        if (response.ok) {
          const parsed = await response.json();
          // Ensure we don't duplicate INITIAL_NEWS if they were somehow saved
          const customPosts = parsed.filter((p: NewsPost) => !INITIAL_NEWS.find(initial => initial.id === p.id));
          setPosts([...INITIAL_NEWS, ...customPosts]);
        }
      } catch (e) {
        console.error("Failed to fetch news from API", e);
        setPosts(INITIAL_NEWS);
      }
    };
    fetchPosts();
  }, []);

  const saveToStorage = async (newPosts: NewsPost[]) => {
    // We only want to save custom posts to the database, not INITIAL_NEWS
    const customPosts = newPosts.filter(p => !INITIAL_NEWS.find(initial => initial.id === p.id));
    
    try {
      const response = await fetch('/api/news', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(customPosts)
      });
      
      if (response.ok) {
        setPosts(newPosts);
        setSuccess('Post published to the cosmos!');
      } else {
        const data = await response.json();
        setError(data.error || 'Failed to save to the celestial database.');
      }
    } catch (e) {
      setError('Connection to the database lost.');
    }
  };

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = e.target.files;
    if (!files || files.length === 0) return;

    const file = files[0];
    if (file.size > 1024 * 1024) {
      setError('File is too large. Please use images under 1MB.');
      return;
    }

    const reader = new FileReader();
    reader.onloadend = () => {
      const base64String = reader.result as string;
      if (formData.format === 'series') {
        setFormData(prev => ({
          ...prev,
          images: [...(prev.images || []), base64String],
          imageUrl: prev.imageUrl || base64String
        }));
      } else {
        setFormData(prev => ({ ...prev, imageUrl: base64String }));
      }
    };
    reader.readAsDataURL(file);
  };

  const removeSeriesImage = (index: number) => {
    setFormData(prev => {
      const newImages = [...(prev.images || [])];
      newImages.splice(index, 1);
      return {
        ...prev,
        images: newImages,
        imageUrl: prev.imageUrl === prev.images?.[index] ? (newImages[0] || '') : prev.imageUrl
      };
    });
  };

  const startEditing = (post: NewsPost) => {
    setEditingId(post.id);
    setFormData({
      ...post,
      images: post.images || []
    });
    window.scrollTo({ top: 0, behavior: 'smooth' });
  };

  const cancelEditing = () => {
    setEditingId(null);
    setFormData({
      format: 'fact',
      topic: 'astrology',
      date: new Date().toISOString().split('T')[0],
      images: []
    });
  };

  const handleAiGenerate = async () => {
    setIsGenerating(true);
    setError('');
    try {
      const forecast = await generateDailyForecast(aiLang, aiPrompt);
      setFormData({
        ...formData,
        title: forecast.title,
        text: forecast.text,
        imageUrl: forecast.imageUrl,
        format: 'forecast',
        topic: 'astrology'
      });
      setSuccess(`Cosmic forecast generated by AI in ${aiLang}!`);
      setAiPrompt(''); // Clear prompt after use
    } catch (err) {
      setError('Failed to connect to the celestial realms. Check API key.');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setError('');
    setSuccess('');

    if (!formData.title || !formData.text || (!formData.imageUrl && !formData.videoUrl)) {
      setError('Please fill in required fields (Title, Text, and either Image or Video)');
      return;
    }

    let updatedPosts: NewsPost[];
    if (editingId) {
      updatedPosts = posts.map(p => p.id === editingId ? {
        ...p,
        title: formData.title!,
        text: formData.text!,
        imageUrl: formData.imageUrl || '',
        videoUrl: formData.videoUrl,
        format: formData.format as PostFormat,
        topic: formData.topic as any,
        date: formData.date || new Date().toISOString().split('T')[0],
        images: formData.format === 'series' ? (formData.images && formData.images.length > 0 ? formData.images : [formData.imageUrl!]) : undefined
      } : p);
      setSuccess('Post updated in the cosmos!');
    } else {
      const newPost: NewsPost = {
        id: Math.random().toString(36).substring(7),
        title: formData.title!,
        text: formData.text!,
        imageUrl: formData.imageUrl || '',
        videoUrl: formData.videoUrl,
        format: formData.format as PostFormat,
        topic: formData.topic as any,
        date: formData.date || new Date().toISOString().split('T')[0],
        images: formData.format === 'series' ? (formData.images && formData.images.length > 0 ? formData.images : [formData.imageUrl!]) : undefined
      };
      updatedPosts = [newPost, ...posts];
      setSuccess('Post published to the cosmos!');
    }

    saveToStorage(updatedPosts);
    cancelEditing();
  };

  const deletePost = (id: string) => {
    if (confirm('Are you sure you want to delete this post?')) {
      const updated = posts.filter(p => p.id !== id);
      saveToStorage(updated);
    }
  };

  return (
    <div className="max-w-7xl mx-auto px-6 py-12">
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-12">
        <div>
          <h1 className="text-4xl font-cinzel font-bold text-cosmic-gold mb-2">Oracle Admin Panel</h1>
          <p className="text-cosmic-silver">Manage the Cosmic News & Forecasts stream.</p>
        </div>
        <div className="flex flex-col md:flex-row gap-4 items-end">
          <div className="flex flex-col gap-1.5">
            <label className="text-[10px] font-bold uppercase tracking-widest text-cosmic-silver">Language</label>
            <select 
              className="bg-cosmic-900/50 border border-cosmic-gold/20 rounded-xl p-3 text-white text-sm focus:outline-none focus:border-cosmic-gold transition-all w-full md:w-32"
              value={aiLang}
              onChange={e => setAiLang(e.target.value as ReportLanguage)}
            >
              <option value="English">English</option>
              <option value="Russian">Russian</option>
              <option value="Ukrainian">Ukrainian</option>
              <option value="French">French</option>
              <option value="German">German</option>
              <option value="Spanish">Spanish</option>
              <option value="Italian">Italian</option>
            </select>
          </div>
          <div className="flex flex-col gap-1.5">
            <label className="text-[10px] font-bold uppercase tracking-widest text-cosmic-silver">AI Focus (Optional)</label>
            <input 
              type="text"
              className="bg-cosmic-900/50 border border-cosmic-gold/20 rounded-xl p-3 text-white text-sm focus:outline-none focus:border-cosmic-gold transition-all w-full md:w-64"
              placeholder="e.g., Full Moon in Leo..."
              value={aiPrompt}
              onChange={e => setAiPrompt(e.target.value)}
            />
          </div>
          <button 
            onClick={handleAiGenerate}
            disabled={isGenerating}
            className="flex items-center gap-2 px-6 py-3 bg-cosmic-purple/20 border border-cosmic-purple/40 text-cosmic-purple hover:bg-cosmic-purple/30 rounded-xl transition-all disabled:opacity-50 h-[46px]"
          >
            {isGenerating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Sparkles className="w-5 h-5" />}
            Generate AI Forecast
          </button>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
        {/* FORM */}
        <div className="space-y-6">
          <form onSubmit={handleSubmit} className="bg-cosmic-900/40 backdrop-blur-xl border border-cosmic-gold/10 rounded-2xl p-8">
            <div className="flex items-center justify-between mb-6">
              <h2 className="text-xl font-cinzel font-bold text-white flex items-center gap-2">
                {editingId ? <Edit3 className="w-5 h-5 text-cosmic-gold" /> : <Plus className="w-5 h-5 text-cosmic-gold" />}
                {editingId ? 'Edit Transmission' : 'New Transmission'}
              </h2>
              <div className="flex gap-2">
                <button 
                  type="button"
                  onClick={() => setShowPreview(!showPreview)}
                  className={`p-2 rounded-lg border transition-all ${showPreview ? 'bg-cosmic-gold text-cosmic-900 border-cosmic-gold' : 'border-cosmic-gold/20 text-cosmic-gold'}`}
                  title="Toggle Preview"
                >
                  <Eye className="w-5 h-5" />
                </button>
                {editingId && (
                  <button 
                    type="button"
                    onClick={cancelEditing}
                    className="p-2 border border-red-500/20 text-red-400 rounded-lg hover:bg-red-500/10 transition-all"
                  >
                    <X className="w-5 h-5" />
                  </button>
                )}
              </div>
            </div>

            {error && (
              <div className="mb-6 p-4 bg-red-500/10 border border-red-500/20 text-red-400 text-sm rounded-lg flex items-center gap-2">
                <AlertCircle className="w-4 h-4" /> {error}
              </div>
            )}

            {success && (
              <div className="mb-6 p-4 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 text-sm rounded-lg flex items-center gap-2">
                <Save className="w-4 h-4" /> {success}
              </div>
            )}

            <div className="space-y-6">
              <div>
                <label className="block text-[10px] font-bold uppercase tracking-widest text-cosmic-silver mb-2">Title</label>
                <input 
                  type="text"
                  className="w-full bg-cosmic-900/50 border border-cosmic-gold/20 rounded-lg p-4 text-white focus:outline-none focus:border-cosmic-gold transition-all text-lg font-cinzel"
                  value={formData.title || ''}
                  onChange={e => setFormData({...formData, title: e.target.value})}
                  placeholder="The Saturn Shift..."
                />
              </div>

              <div>
                <label className="block text-[10px] font-bold uppercase tracking-widest text-cosmic-silver mb-2">Content</label>
                <textarea 
                  rows={12}
                  className="w-full bg-cosmic-900/50 border border-cosmic-gold/20 rounded-lg p-4 text-white focus:outline-none focus:border-cosmic-gold transition-all resize-y font-inter leading-relaxed"
                  value={formData.text || ''}
                  onChange={e => setFormData({...formData, text: e.target.value})}
                  placeholder="Describe the celestial event in detail..."
                />
              </div>

              <div className="grid grid-cols-2 gap-4">
                <div>
                  <label className="block text-[10px] font-bold uppercase tracking-widest text-cosmic-silver mb-2">Format</label>
                  <select 
                    className="w-full bg-cosmic-900/50 border border-cosmic-gold/20 rounded-lg p-3 text-white focus:outline-none focus:border-cosmic-gold transition-all"
                    value={formData.format}
                    onChange={e => setFormData({...formData, format: e.target.value as PostFormat, images: []})}
                  >
                    <option value="fact">Fact (Small)</option>
                    <option value="forecast">Forecast (Large)</option>
                    <option value="series">Series (Slider)</option>
                  </select>
                </div>
                <div>
                  <label className="block text-[10px] font-bold uppercase tracking-widest text-cosmic-silver mb-2">Topic</label>
                  <select 
                    className="w-full bg-cosmic-900/50 border border-cosmic-gold/20 rounded-lg p-3 text-white focus:outline-none focus:border-cosmic-gold transition-all"
                    value={formData.topic}
                    onChange={e => setFormData({...formData, topic: e.target.value as any})}
                  >
                    <option value="astrology">Astrology</option>
                    <option value="numerology">Numerology</option>
                    <option value="astronomy">Astronomy</option>
                  </select>
                </div>
              </div>

              <div>
                <label className="block text-[10px] font-bold uppercase tracking-widest text-cosmic-silver mb-2">Media</label>
                <div className="space-y-4">
                  <div className="flex flex-col gap-2">
                    <div className="flex gap-2">
                      <input 
                        type="text"
                        className="flex-1 bg-cosmic-900/50 border border-cosmic-gold/20 rounded-lg p-3 text-white text-xs focus:outline-none focus:border-cosmic-gold transition-all"
                        value={formData.imageUrl || ''}
                        onChange={e => setFormData({...formData, imageUrl: e.target.value})}
                        placeholder="Image URL or Upload..."
                      />
                      <button 
                        type="button"
                        onClick={() => fileInputRef.current?.click()}
                        className="p-3 bg-cosmic-gold/10 border border-cosmic-gold/20 rounded-lg text-cosmic-gold hover:bg-cosmic-gold/20 transition-all"
                      >
                        <Upload className="w-5 h-5" />
                      </button>
                      <input 
                        type="file" 
                        ref={fileInputRef} 
                        className="hidden" 
                        accept="image/*" 
                        onChange={handleFileUpload}
                      />
                    </div>
                    
                    {formData.imageUrl && formData.format !== 'series' && (
                      <div className="relative w-full h-32 rounded-lg overflow-hidden border border-cosmic-gold/20">
                        <img src={formData.imageUrl} alt="Preview" className="w-full h-full object-cover" />
                        <button 
                          type="button"
                          onClick={() => setFormData({...formData, imageUrl: ''})}
                          className="absolute top-2 right-2 p-1 bg-red-500 text-white rounded-full"
                        >
                          <X className="w-4 h-4" />
                        </button>
                      </div>
                    )}

                    {formData.format === 'series' && formData.images && formData.images.length > 0 && (
                      <div className="grid grid-cols-4 gap-2">
                        {formData.images.map((img, idx) => (
                          <div key={idx} className="relative aspect-square rounded-lg overflow-hidden border border-cosmic-gold/20">
                            <img src={img} alt={`Preview ${idx}`} className="w-full h-full object-cover" />
                            <button 
                              type="button"
                              onClick={() => removeSeriesImage(idx)}
                              className="absolute top-1 right-1 p-1 bg-red-500 text-white rounded-full"
                            >
                              <X className="w-3 h-3" />
                            </button>
                          </div>
                        ))}
                      </div>
                    )}
                  </div>

                  <div className="flex items-center gap-2">
                    <Youtube className="w-5 h-5 text-red-500 shrink-0" />
                    <input 
                      type="text"
                      className="w-full bg-cosmic-900/50 border border-cosmic-gold/20 rounded-lg p-3 text-white text-xs focus:outline-none focus:border-cosmic-gold transition-all"
                      value={formData.videoUrl || ''}
                      onChange={e => setFormData({...formData, videoUrl: e.target.value})}
                      placeholder="YouTube URL (optional)"
                    />
                  </div>
                </div>
              </div>

              <div>
                <label className="block text-[10px] font-bold uppercase tracking-widest text-cosmic-silver mb-2">Date</label>
                <input 
                  type="date"
                  className="w-full bg-cosmic-900/50 border border-cosmic-gold/20 rounded-lg p-3 text-white focus:outline-none focus:border-cosmic-gold transition-all"
                  value={formData.date || ''}
                  onChange={e => setFormData({...formData, date: e.target.value})}
                />
              </div>

              <button 
                type="submit"
                className="w-full py-4 bg-cosmic-gold text-cosmic-900 font-cinzel font-bold rounded-xl hover:bg-white transition-all active:scale-95 shadow-lg shadow-cosmic-gold/20"
              >
                {editingId ? 'Update Transmission' : 'Publish Post'}
              </button>
            </div>
          </form>
        </div>

        {/* LIST OR PREVIEW */}
        <div className="space-y-8">
          {showPreview ? (
            <div className="sticky top-24">
              <h2 className="text-xl font-cinzel font-bold text-white mb-6 flex items-center gap-2">
                <Eye className="w-5 h-5 text-cosmic-gold" /> Live Preview
              </h2>
              <div className="antique-paper p-8 rounded-3xl shadow-2xl border border-cosmic-gold/30 min-h-[600px]">
                <div className="ornate-border p-8 h-full">
                  <div className="flex items-center gap-4 mb-6">
                    <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-cosmic-gold px-2 py-0.5 bg-cosmic-gold/10 rounded border border-cosmic-gold/20">
                      {formData.topic}
                    </span>
                    <span className="text-[10px] font-bold uppercase tracking-[0.2em] text-[#666] flex items-center gap-1">
                      <Calendar className="w-3 h-3" /> {formData.date}
                    </span>
                  </div>
                  
                  {formData.imageUrl && (
                    <div className="w-full aspect-video rounded-xl overflow-hidden mb-8 border border-black/10">
                      <img src={formData.imageUrl} alt="" className="w-full h-full object-cover" />
                    </div>
                  )}

                  <h3 className="text-3xl font-cinzel font-bold text-[#1a1a1a] mb-6 leading-tight">{formData.title || 'Untitled Transmission'}</h3>
                  <div className="prose prose-stone max-w-none">
                    <div className="text-[#333] font-inter text-lg leading-relaxed markdown-body">
                      <Markdown>{formData.text || 'Begin your cosmic transmission...'}</Markdown>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div className="bg-cosmic-900/40 backdrop-blur-xl border border-cosmic-gold/10 rounded-2xl overflow-hidden">
              <div className="p-6 border-b border-cosmic-gold/10 bg-white/5 flex items-center justify-between">
                <h2 className="text-xl font-cinzel font-bold text-white">Active Transmissions ({posts.length})</h2>
              </div>
              <div className="divide-y divide-cosmic-gold/10 max-h-[800px] overflow-y-auto">
                {posts.length === 0 ? (
                  <div className="p-20 text-center text-cosmic-silver italic">
                    No custom posts found. The cosmic stream is empty.
                  </div>
                ) : (
                  posts.map(post => (
                    <div key={post.id} className={`p-6 flex items-center justify-between gap-6 hover:bg-white/5 transition-all ${editingId === post.id ? 'bg-cosmic-gold/5 border-l-4 border-l-cosmic-gold' : ''}`}>
                      <div className="flex items-center gap-4">
                        <div className="w-16 h-16 rounded-lg overflow-hidden border border-cosmic-gold/20 shrink-0 bg-cosmic-800 flex items-center justify-center">
                          {post.imageUrl ? (
                            <img src={post.imageUrl} alt="" className="w-full h-full object-cover" />
                          ) : post.videoUrl ? (
                            <Youtube className="w-8 h-8 text-red-500" />
                          ) : (
                            <ImageIcon className="w-8 h-8 text-cosmic-gold/20" />
                          )}
                        </div>
                        <div>
                          <h4 className="text-white font-bold mb-1 line-clamp-1">{post.title}</h4>
                          <div className="flex gap-3 text-[10px] font-bold uppercase tracking-widest text-cosmic-silver">
                            <span className="flex items-center gap-1"><Layout className="w-3 h-3" /> {post.format}</span>
                            <span className="flex items-center gap-1"><Calendar className="w-3 h-3" /> {post.date}</span>
                          </div>
                        </div>
                      </div>
                      <div className="flex gap-2">
                        <button 
                          onClick={() => startEditing(post)}
                          className="p-3 text-cosmic-gold hover:bg-cosmic-gold/10 rounded-full transition-all"
                          title="Edit Post"
                        >
                          <Edit3 className="w-5 h-5" />
                        </button>
                        <button 
                          onClick={() => deletePost(post.id)}
                          className="p-3 text-red-400 hover:bg-red-500/10 rounded-full transition-all"
                          title="Delete Post"
                        >
                          <Trash2 className="w-5 h-5" />
                        </button>
                      </div>
                    </div>
                  ))
                )}
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AdminPanel;
