import React from 'react';
import { ReportLanguage } from '../types';
import { translations } from '../translations';
import { HelpCircle, ChevronDown } from 'lucide-react';

interface FAQSectionProps {
  language: ReportLanguage;
}

const FAQSection: React.FC<FAQSectionProps> = ({ language }) => {
  const t = translations[language] || translations['English'];
  
  const faqs = [
    {
      q: "Is registration required for a natal chart?",
      a: "No, Atlantic Oracle provides high-precision natal chart calculations without any registration. We value your ephemeral privacy and do not collect emails or personal data for tracking."
    },
    {
      q: "How does the daily vibration forecast work?",
      a: "Our system synthesizes current planetary transits with Pythagorean numerical vibrations to provide a unique daily forecast for each soul. It's a blend of celestial mechanics and mathematical precision."
    },
    {
      q: "What is the 'Weather/Engine' philosophy?",
      a: "We view Astrology as the 'Weather' (the external environment and timing) and Numerology as the 'Engine' (your internal drive and structural vibration). Together, they provide a complete map of your existence."
    },
    {
      q: "Are the reports generated by AI?",
      a: "Yes, we use advanced AI models (Gemini) trained on professional astrological and numerological data to synthesize complex readings into readable, professional reports."
    }
  ];

  return (
    <section id="faq" className="px-6 max-w-4xl mx-auto py-20">
      <div className="text-center mb-16 space-y-4">
        <div className="inline-flex items-center gap-2 px-4 py-1 bg-cosmic-gold/10 border border-cosmic-gold/20 rounded-full text-[10px] font-bold text-cosmic-gold uppercase tracking-[0.3em]">
          <HelpCircle className="w-3 h-3" />
          Common Inquiries
        </div>
        <h2 className="text-3xl md:text-4xl font-cinzel text-white uppercase tracking-widest">Frequently Asked Questions</h2>
        <div className="w-24 h-px bg-gradient-to-r from-transparent via-cosmic-gold to-transparent mx-auto"></div>
      </div>

      <div className="space-y-4">
        {faqs.map((faq, i) => (
          <details key={i} className="group bg-cosmic-800/10 border border-cosmic-gold/10 rounded-3xl overflow-hidden transition-all hover:border-cosmic-gold/30">
            <summary className="flex items-center justify-between p-6 cursor-pointer list-none">
              <span className="text-white font-cinzel text-sm md:text-base tracking-wide uppercase">{faq.q}</span>
              <ChevronDown className="w-5 h-5 text-cosmic-gold group-open:rotate-180 transition-transform" />
            </summary>
            <div className="px-6 pb-6 text-cosmic-silver/80 font-light text-sm leading-relaxed italic border-t border-cosmic-gold/5 pt-4">
              {faq.a}
            </div>
          </details>
        ))}
      </div>
    </section>
  );
};

export default FAQSection;
